### ISSUE TITLE
options.seeds variable undefined

### ISSUE THREAD

**Issue by Oldenborg** [matejsvajger/laravel-mix-pug#2]
Installing this repo and using it without the third "optional" option results in an error.

```
/Users/Oldenborg/Code/warhammerhygge/node_modules/laravel-mix-pug/src/MixPugTask.js:25
        this.seedPath = options.seeds;
                               ^

TypeError: Cannot read property 'seeds' of null
    at MixPugTask.run (/Users/Oldenborg/Code/warhammerhygge/node_modules/laravel-mix-pug/src/MixPugTask.js:25:32)
    at CustomTasksPlugin.runTask (/Users/Oldenborg/Code/warhammerhygge/node_modules/laravel-mix/src/plugins/CustomTasksPlugin.js:34:14)
    at Mix.tasks.forEach.task (/Users/Oldenborg/Code/warhammerhygge/node_modules/laravel-mix/src/plugins/CustomTasksPlugin.js:9:44)
    at Array.forEach (native)
    at Compiler.compiler.plugin.stats (/Users/Oldenborg/Code/warhammerhygge/node_modules/laravel-mix/src/plugins/CustomTasksPlugin.js:9:23)
    at Compiler.applyPlugins (/Users/Oldenborg/Code/warhammerhygge/node_modules/tapable/lib/Tapable.js:61:14)
    at Watching._done (/Users/Oldenborg/Code/warhammerhygge/node_modules/webpack/lib/Compiler.js:104:17)
    at compiler.emitRecords.err (/Users/Oldenborg/Code/warhammerhygge/node_modules/webpack/lib/Compiler.js:78:19)
    at Compiler.emitRecords (/Users/Oldenborg/Code/warhammerhygge/node_modules/webpack/lib/Compiler.js:375:38)
    at compiler.emitAssets.err (/Users/Oldenborg/Code/warhammerhygge/node_modules/webpack/lib/Compiler.js:61:20)
    at applyPluginsAsyncSeries1.err (/Users/Oldenborg/Code/warhammerhygge/node_modules/webpack/lib/Compiler.js:368:12)
    at next (/Users/Oldenborg/Code/warhammerhygge/node_modules/tapable/lib/Tapable.js:218:11)
    at Compiler.compiler.plugin (/Users/Oldenborg/Code/warhammerhygge/node_modules/webpack/lib/performance/SizeLimitsPlugin.js:99:4)
    at Compiler.applyPluginsAsyncSeries1 (/Users/Oldenborg/Code/warhammerhygge/node_modules/tapable/lib/Tapable.js:222:13)
    at Compiler.afterEmit (/Users/Oldenborg/Code/warhammerhygge/node_modules/webpack/lib/Compiler.js:365:9)
    at require.forEach.err (/Users/Oldenborg/Code/warhammerhygge/node_modules/webpack/lib/Compiler.js:354:15)
    at /Users/Oldenborg/Code/warhammerhygge/node_modules/async/dist/async.js:421:16
    at iteratorCallback (/Users/Oldenborg/Code/warhammerhygge/node_modules/async/dist/async.js:998:13)
    at /Users/Oldenborg/Code/warhammerhygge/node_modules/async/dist/async.js:906:16
    at /Users/Oldenborg/Code/warhammerhygge/node_modules/graceful-fs/graceful-fs.js:43:10
    at FSReqWrap.oncomplete (fs.js:112:15)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ watch: `cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --watch --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ watch script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
```

I fixed it by setting default values like this in `MixPugTask.js`
```js
if(!options) {
    options  = {
         seeds: '',
         locals: {}
    };
}
```

And I also changed

```js
    // Setup template seeder
    this.seedPath = options.seeds;
    this.locals = options.locals || {};

    // changed to this
    this.seedPath = options.seeds;
    this.locals = options.locals;

```

**Comment by simonvomeyser** [comment]
Having the same problem.. can you maybe issue a pull request? Thank you for your hint @Oldenborg! 

For everyone stumbling across this issue: Define the third option with an empty object is a hotfix

```js
mix.pug('templates/*.pug', 'build', {});
```

**Comment by matejsvajger** [comment]
Thanks for reporting this.

I'll squeeze some time tomorrow to get this in.

**Comment by matejsvajger** [comment]
49c183bc7cff207db9504750ee71663a53d5c7d3 resolves this issue.

**Comment by simonvomeyser** [comment]
Thank you so much and keep up the good work 👍

**Comment by Oldenborg** [comment]
Thanks, did not know if my solution was the right one, so I did not want to make a pull request for it. But happy to se it go resolved.
